## .travis.yml
##

#sudo: required

language: c

install:
#  # some location to install and use lcov
#  - cd ${TRAVIS_BUILD_DIR}
#  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
#  - tar xf lcov_1.11.orig.tar.gz
#  - sudo make -C lcov-1.11/ install

#before_script:
#  - cd ${TRAVIS_BUILD_DIR}
#  - lcov --directory . --zerocounters

# Compiler selection
compiler:
  - gcc
  - clang

script:
  - cd 30__c__pthreads/pthread__join02 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__signalhandler02 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__stack-management && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__create && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__condition-var02 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__condition-var00 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__mutex01 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__restaurant && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__signalhandler01 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__hello_world && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__mutex00 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__mutex02 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__producer-consumer && make && ./*.exe ./source.txt ./destination.txt && cd -
  - cd 30__c__pthreads/pthread__rwlock && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__condition-var01 && make && ./*.exe && cd -
  - cd 30__c__pthreads/semaphore__ipc-synchronization && make && ./*.exe && cd -

  ## needs command line arguments
  - cd 30__c__pthreads/pthread__passing-arguments01 && make && cd -
  - cd 30__c__pthreads/pthread__passing-arguments02 && make && cd -
  - cd 30__c__pthreads/pthread__passing-arguments03 && make && cd -
  - cd 30__c__pthreads/pthread__six-threads && make1 && cd -
  - cd 30__c__pthreads/pthread__deadlock && make && cd -
  - cd 30__c__pthreads/pthread__manythreads && make && cd -

  ## server, thus waiting for connection
  - cd 30__c__pthreads/pthread__socket-server && make && cd -

  ## thread cancellation, to be watched on top
  - cd 30__c__pthreads/pthread__posix-cancellation && make && cd -

  ## travis seems to have trouble with the following, thus just compiling
  - cd 30__c__pthreads/pthread__join00 && make && cd -
  - cd 30__c__pthreads/pthread__join01 && make && ./*.exe && cd -


# after_success:
#   - cd ${TRAVIS_BUILD_DIR}
#   - lcov --directory . --capture --output-file coverage.info # capture coverage info
#   - lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info # filter out system and test code
#   - lcov --list coverage.info # debug before upload
#   #- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls.. for a private repo using a token
#   - coveralls-lcov  coverage.info #for open source
