## .travis.yml
##

#sudo: required

language: c

before_install:
  - sudo apt-get install -y nasm

install:
#  # some location to install and use lcov
#  - cd ${TRAVIS_BUILD_DIR}
#  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
#  - tar xf lcov_1.11.orig.tar.gz
#  - sudo make -C lcov-1.11/ install


#before_script:
#  - cd ${TRAVIS_BUILD_DIR}
#  - lcov --directory . --zerocounters

# Compiler selection
compiler:
  - gcc
  - clang

script:
## 00: basics
  - cd ./00__c__language-basics/atoi02 && make && ./*.exe && cd -
  - cd ./00__c__language-basics/2dim__pointer-to-pointer && make && ./*.exe && cd -
  - cd ./00__c__language-basics/pointer__arithmetics && make && ./*.exe && cd -
  - cd ./00__c__language-basics/atoi01 && make && ./*.exe && cd -
  - cd ./00__c__language-basics/2dim__array-of-array && make && ./*.exe && cd -
  - cd ./00__c__language-basics/argumentlist && make && ./*.exe && cd -
  - cd ./00__c__language-basics/2dim__pointer-to-array && make && ./*.exe && cd -
  - cd ./00__c__language-basics/void-pointer && make && ./*.exe && cd -
  - cd ./00__c__language-basics/allocation && make && ./*.exe && cd -
  - cd ./00__c__language-basics/HelloWorld && make && ./*.exe && cd -
  - cd ./00__c__language-basics/string-to-int-to-string && make && ./*.exe && cd -
  - cd ./00__c__language-basics/struct && make && ./*.exe && cd -
  - cd ./00__c__language-basics/pointer__assignment && make && ./*.exe && cd -
  - cd ./00__c__language-basics/preprocessor && make && ./*.exe && cd -

  ## interactive example
  - cd ./00__c__language-basics/function-pointer && make && cd -


## 10: techniques
  - cd ./10__c__language-techniques/dequeue && make && ./*.exe && cd -
  - cd ./10__c__language-techniques/endianness && make && ./*.exe && cd -
  - cd ./10__c__language-techniques/file__operations && make && ./*.exe && cd -
  - cd ./10__c__language-techniques/file__tempfile && make && ./*.exe && cd -
  - cd ./10__c__language-techniques/stdout__fflush-printf-order && make && ./*.exe && cd -
  - cd ./10__c__language-techniques/debug__mtrace && make && ./*.exe && cd -
#  - cd ./10__c__language-techniques/debug__valgrind-double-free && make && ./*.exe && cd - ## has to fail
  - cd ./10__c__language-techniques/debug__valgrind-invalid-pointer && make && ./*.exe && cd -
#  - cd ./10__c__language-techniques/debug__valgrind-mem-leak01 && make && ./*.exe && cd -
  - cd ./10__c__language-techniques/debug__valgrind-mem-leak02 && make && ./*.exe && cd -
  - cd ./10__c__language-techniques/debug__valgrind-uninitialized && make && ./*.exe && cd -

  ## interactive and/or need fixes
  - cd ./10__c__language-techniques/bintree__demo-TODO && make && cd -
  - cd ./10__c__language-techniques/bintree__single-linked-TODO && make && cd -
  - cd ./10__c__language-techniques/bitoperations-FIXME && make && cd -
  - cd ./10__c__language-techniques/input && make && cd -
  - cd ./10__c__language-techniques/input__fgets-digit && make && cd -
  - cd ./10__c__language-techniques/input__fgets-number && make && cd -
  - cd ./10__c__language-techniques/input__fgetc-number && make && cd -
  - cd ./10__c__language-techniques/input__fgetc-string && make && cd -
  - cd ./10__c__language-techniques/input__choice && make && cd -
  - cd ./10__c__language-techniques/file__filesize && make && cd -
  - cd ./10__c__language-techniques/file__fseek-position && make && cd -
  - cd ./10__c__language-techniques/stdin__fflush-undefined && make && cd -
  - cd ./10__c__language-techniques/file__fsetpos && make && cd -
  - cd ./10__c__language-techniques/file__move && make && cd -
  - cd ./10__c__language-techniques/input__getch && make && cd -


## 30: pthreads
  - cd 30__c__pthreads/pthread__join02 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__signalhandler02 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__stack-management && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__create && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__condition-var02 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__condition-var00 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__mutex01 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__restaurant && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__signalhandler01 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__hello_world && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__mutex00 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__mutex02 && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__producer-consumer && make && ./*.exe ./source.txt ./destination.txt && cd -
  - cd 30__c__pthreads/pthread__rwlock && make && ./*.exe && cd -
  - cd 30__c__pthreads/pthread__condition-var01 && make && ./*.exe && cd -
  - cd 30__c__pthreads/semaphore && make && ./*.exe && cd -
  - cd 30__c__pthreads/semaphore__semctl && make && cd -
#  - cd 30__c__pthreads/semaphore__semget && make && cd -
  - cd 30__c__pthreads/semaphore__ipc-synchronization && make && ./*.exe && cd -

  ## needs command line arguments
  - cd 30__c__pthreads/pthread__passing-arguments01 && make && cd -
  - cd 30__c__pthreads/pthread__passing-arguments02 && make && cd -
  - cd 30__c__pthreads/pthread__passing-arguments03 && make && cd -
  - cd 30__c__pthreads/pthread__six-threads && make && cd -
  - cd 30__c__pthreads/pthread__deadlock && make && cd -
  - cd 30__c__pthreads/pthread__manythreads && make && cd -

  ## server, thus waiting for connection
  - cd 30__c__pthreads/pthread__socket-server && make && cd -

  ## thread cancellation, to be watched on top
  - cd 30__c__pthreads/pthread__posix-cancellation && make && cd -

  ## travis seems to have trouble with the following, thus just compiling
  - cd 30__c__pthreads/pthread__join00 && make && cd -
  - cd 30__c__pthreads/pthread__join01 && make && ./*.exe && cd -


## 40: linux (all just built, since execution in case needs runs in parallel
  - cd 40__c__linux/ptrace__010-fork-show-all-instructions && make && cd -
  - cd 40__c__linux/ptrace__020-fork-syswrite-peekuser && make && cd -
  - cd 40__c__linux/ptrace__021-fork-syswrite-peekuser-getregs && make && cd -
  - cd 40__c__linux/ptrace__030-fork-syswrite-peekuser-peekdata-pokedata && make && cd -
  - cd 40__c__linux/ptrace__031-fork-syswrite-getregs-peekdata-pokedata && make && cd -
  - cd 40__c__linux/ptrace__032-fork-getregs-show-syscalls && make && cd -
  - cd 40__c__linux/ptrace__033-fork-getregs-show-syscalls-peekdata-pokedata-change-syswrite && make && cd -
  - cd 40__c__linux/ptrace__034-fork-getregs-show-syscalls-results && make && cd -
  - cd 40__c__linux/ptrace__035-fork-getregs-show-syscalls-inject-result-eperm && make && cd -
  - cd 40__c__linux/ptrace__040-fork-syswrite-getregs-peektext-singlestep && make && cd -
  - cd 40__c__linux/ptrace__041-fork-syswrite-getregs-peektext-singlestep-all-instructions && make && cd -
  - cd 40__c__linux/ptrace__050-attach-detatch && make && cd -
  - cd 40__c__linux/ptrace__051-attach-stop-restart-detach && make && cd -
  - cd 40__c__linux/ptrace__052-attach-stop-inject-restart-detach && make && cd -
  - cd 40__c__linux/ptrace__053-attach-stop-inject-reestablish-restart-detach && make && cd -
  - cd 40__c__linux/ptrace__060-injection-replace && make && cd -
  - cd 40__c__linux/ptrace__070-injection-shift-to-next-free-space && make && cd -
  - cd 40__c__linux/ptrace__100-debugger-loop-instructions && make && cd -
#  - cd 40__c__linux/ptrace__105-singlestep-snippet__FIXME && make && cd -
#  - cd 40__c__linux/ptrace__110-debugger-watchpoint__FIXME && make && cd -
#  - cd 40__c__linux/ptrace__120-debugger-proc__FIXME && make && cd -
#  - cd 40__c__linux/ptrace__130-debugger-singlestep-multithreading__FIXME && make && cd -
  - cd 40__c__linux/asm__00-hello-world && make && cd -
  - cd 40__c__linux/asm__01-add-numbers && make && cd -
  - cd 40__c__linux/asm__02-add-numbers && make && cd -
  - cd 40__c__linux/asm__03-compare-values && make && cd -
  - cd 40__c__linux/asm__04-set-clear-bit && make && cd -
  - cd 40__c__linux/asm__05-strcpy && make && cd -
  - cd 40__c__linux/asm__06-move-block && make && cd -
  - cd 40__c__linux/asm__07-syscall && make && cd -
  - cd 40__c__linux/asm__08-eval-sys-exit && make && cd -
  - cd 40__c__linux/asm__09-syscall-generic && make && cd -
  - cd 40__c__linux/asm__10-string-section && make && cd -
  - cd 40__c__linux/fork__simple && make && cd -
  - cd 40__c__linux/fork__cli-command && make && cd -
  - cd 40__c__linux/fork && make && cd -
  - cd 40__c__linux/execl && make && cd -
  - cd 40__c__linux/execlp && make && cd -
  - cd 40__c__linux/execv && make && cd -
  - cd 40__c__linux/execve && make && cd -
  - cd 40__c__linux/execvp && make && cd -
  - cd 40__c__linux/gid-and-pid && make && cd -
  - cd 40__c__linux/kill && make && cd -
  - cd 40__c__linux/killpg && make && cd -
  - cd 40__c__linux/system && make && cd -
  - cd 40__c__linux/vfork && make && cd -
  - cd 40__c__linux/wait && make && cd -
  - cd 40__c__linux/waitpid && make && cd -
  - cd 40__c__linux/start_javaprg && make && cd -
  - cd 40__c__linux/pid && make && cd -
  - cd 40__c__linux/sharedobject__dynamic-fixed && make && cd -
  - cd 40__c__linux/sharedobject__dynamic-shared && make && cd -
  - cd 40__c__linux/sharedobject__static-lib && make && cd -
  - cd 40__c__linux/timer && make && cd -
  - cd 40__c__linux/timer__measuring && make && cd -


# after_success:
#   - cd ${TRAVIS_BUILD_DIR}
#   - lcov --directory . --capture --output-file coverage.info # capture coverage info
#   - lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info # filter out system and test code
#   - lcov --list coverage.info # debug before upload
#   #- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls.. for a private repo using a token
#   - coveralls-lcov  coverage.info #for open source
