## Makefile (simple)
##
## @author: Lothar Rubusch
## @email: L.Rubusch@gmx.ch
## @license: GPLv3
##
## use -O, -O1, -O2 for optimization


SOURCE = select.c
OBJECTS = ${SOURCE:.c=.o}

.PREFIXES = .c .o
CC = gcc
CFLAGS = -g -Wall -std=c99 -pedantic
RM = rm -f

.c.o:
	${CC} -c ${CFLAGS} $<

select.exe: ${OBJECTS}
	${CC} -o $@ ${OBJECTS} -lm

all: select.exe

clean:
	${RM} $(OBJECTS) select.exe *~ core


